config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  resources :courses do
    resources :course_units
    resources :teachings, only: [:create, :destroy]
    resources :studyings, only: [:create, :destroy]
    resources :invitations, only: [:create, :destroy]
  end

  resources :users, except: [:edit, :update] do
    get :edit, on: :collection
    patch :update, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :course_resources do
    resources :submissions
  end

 resources :contact

 resources :kinds

 resources :course_units do
   resources :course_resources
 end

 resources :password_requests, only: [:new, :create]

 get "password/reset" => "password_requests#reset"

 resources :scores, only: [:create, :update]

end

app/models/course_resource.rb
class CourseResource < ActiveRecord::Base

  belongs_to :kind
  belongs_to :course_unit

  has_many :submissions

  has_many :scores, dependent: :destroy
  has_many :scored_users, through: :scores, source: :user

  validates :kind, presence: true
  validates :title, presence: true
  validates :content, presence: true

  mount_uploader :resource_file, ResourceFileUploader

  def authorize
    unless can? :manage, @course_resource
      redirect_to root_path, alert: "Access denied buddy!"
    end
  end


end

app/controllers/course_resources_controller.rb
class CourseResourcesController < ApplicationController
  before_action :find_course_unit,  only: [:new, :index, :create, :update]

  def new
    @course_resource = CourseResource.new
  end

  def index
    @course_resources = CourseResource.all
  end

  def create
    course_resource_params = params.require(:course_resource).permit([:title, :content, :kind_id, :resource_file])
    @course_resource = CourseResource.new(course_resource_params)
    if @course_resource.save
      redirect_to course_unit_course_resource_path(@course_unit, @course_resource)
    else
      render :new
    end
  end

  def show
    @course_resource = CourseResource.find params[:id]
    @submission = Submission.new
    @course_unit = CourseUnit.find(@course_resource.course_unit.id)
  end

  def edit
    @course_resource = CourseResource.find params[:id]
  end

  def update
    @course_resource = CourseResource.find params[:id]
    course_resource_params = params.require(:course_resource).permit([:title,
                                  :content, :kind_id, :resource_file, :hidden])
    if @course_resource.update(course_resource_params)
      if course_resource_params[:hidden] != nil
        redirect_to course_path(@course_resource.course_unit.course)
      else
        redirect_to course_unit_course_resource_path(@course_unit, @course_resource)
      end
    else
      render :update
    end
  end

  def destroy
    @course_resource = CourseResource.find params[:id]
    @course_resource.destroy
    redirect_to course_unit_path(@course_unit)
  end

  private

  def find_course_unit
    @course_unit ||= CourseUnit.find params[:course_unit_id]
  end


end

app/helpers/course_resources_helper.rb
module CourseResourcesHelper
end

app/views/course_resources/_form.html.erb
  <%= simple_form_for [@course_unit,@course_resource] do |f| %>
    <%= f.input :title %>
    <%= f.association :kind, collection: Kind.all, label_method: :title, value_method: :id, prompt: "Choose Resource Type" %>
    <%= f.input :content %>
    <%= f.input :resource_file %>
    <%= f.submit "Submit", :class => "btn label-warning" %>
  <% end %>

app/views/course_resources/_resource.html.erb
<% course_unit.course_resources.each do |course_resource| %>
  <p><%= link_to course_resource.title, course_unit_course_resource_path(course_unit, course_resource) %>
    <% if current_user && current_user.admin? %>
    | <%= link_to "Hide Toggle", course_unit_course_resource_path(course_resource.course_unit,
      course_resource, course_resource: {hidden: !course_resource.hidden}), method: :patch %></p>
    <% end %>
<% end %>
</ul>

app/views/course_resources/edit.html.erb
<div class="col-xs-offset-2 col-xs-8 bottom-out">
  <h1>Edit Course Resource</h1>
  <%= render 'form' %>
</div>

app/views/course_resources/index.html.erb
<h2>Course Resources</h2>

          <li role="presentation" class="label-warning"><%= link_to "Create a  Course Resource", new_course_resource_path %></li>

          <li role="presentation" class="label-warning"><%= link_to "Edit a  Course Resource", edit_course_resource_path(1) %></li>
<hr>
<%= render "resource" %>

app/views/course_resources/new.html.erb
<div class="col-xs-offset-2 col-xs-8 bottom-out">
  <h1>Create Course Resource</h1>
  <%= render 'form' %>
</div>

app/views/course_resources/show.html.erb
<div class="inline">
  <h1><%= @course_resource.title %> (<%= @course_resource.kind.title %>)&nbsp;</h1>
</div>

<%# if can?(:manage, @course_resource) %>
<div class="inline">
   <%= link_to "Edit", edit_course_unit_course_resource_path(@course_unit,@course_resource)  %> | <%= link_to "Delete", course_unit_course_resource_path(@course_unit,@course_resource), method: :delete,
            data:  {confirm: "Are you sure you want to delete the resource?"}  %>
</div>
<%# end %>

<div class="jumbotron-white">
  <div class="well">
    <%= @course_resource.content %>
  </div>
  <% if @course_resource.resource_file.present? %>
    <%= File.basename(@course_resource.resource_file.path)  %> <br /> <%= link_to 'Download file', @course_resource.resource_file.url %>
  <% end %>
</div>
<% if current_user.admin? %>
  <%= link_to "Submissions", course_resource_submissions_path(@course_resource) %>
<% end %>
<% if @course_resource.course_unit %>
  <% if @course_resource.course_unit.course %>
    <% if @course_resource.course_unit.course.students.include? current_user %>
      <div class="jumbotron-white">
        <%= render "/submissions/form" %>
      </div>
    <% end %>
  <% end %>
<% end %>
  <div class="inline">
    <%# button_to "Edit", edit_course_unit_course_resource_path(@course_unit,@course_resource), :class => "btn label-warning"  %>
  </div>
  <div class="inline">
    <%# button_to "Delete", course_unit_course_resource_path(@course_unit,@course_resource), method: :delete, :class => "btn label-warning",
		<%= @course_resource.title %><br />
		<%= @course_resource.kind.title %><br />
		<%= @course_resource.content %>
		<% if @course_resource.resource_file.present? %>
		  <%= File.basename(@course_resource.resource_file.path)  %> | <%= link_to 'Download file', @course_resource.resource_file.url %>
		<% end %>
	</div>