config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  resources :courses do
    resources :course_units
    resources :teachings, only: [:create, :destroy]
    resources :studyings, only: [:create, :destroy]
    resources :invitations, only: [:create, :destroy]
  end

  resources :users, except: [:edit, :update] do
    get :edit, on: :collection
    patch :update, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :course_resources do
    resources :submissions
  end

 resources :contact

 resources :kinds

 resources :course_units do
   resources :course_resources
 end

 resources :password_requests, only: [:new, :create]

 get "password/reset" => "password_requests#reset"

 resources :scores, only: [:create, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    # When admin will be defined, un-comment it
    # if user.admin?
    #   can :manage, :all
    can :manage, CourseUnit do |course_unit|
      user.admin?
    end

    can :manage, CourseResource do |course_resouce|
      user.admin?
    end
    can :manage, Course do |course|
      user.admin?
    end
    can :manage, Kind do |kind|
      user.admin?
    end
    # else

    #  can :manage, CourseUnit do |unit|
    #    unit.user == user
    #  end

    #  can :manage, CourseResource do |resource|
    #    resource.unit.user == user || resource.user == user
    #  end

    # end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/course.rb
class Course < ActiveRecord::Base

	mount_uploader :course_logo, ImageUploader

  belongs_to :user

	has_many :invitations, dependent: :destroy
	has_many :invitees, through: :invitations, source: :invitee
	has_many :teachings, dependent: :destroy
	has_many :teachers, through: :teachings, source: :user

	has_many :studyings, dependent: :destroy
	has_many :students, through: :studyings, source: :user

	has_many :course_units, dependent: :destroy
	has_many :course_resources, through: :course_units

	has_many :invitations, dependent: :destroy

	has_many :syllabuses, dependent: :destroy
	has_many :course_unit_syllabulized, through: :syllabuses, source: :course_unit

  def study_for(user)
    studyings.find_by_user_id(user)
  end

  def teach_for(user)
    teachings.find_by_user_id(user)
  end

end

app/models/course_resource.rb
class CourseResource < ActiveRecord::Base

  belongs_to :kind
  belongs_to :course_unit

  has_many :submissions

  has_many :scores, dependent: :destroy
  has_many :scored_users, through: :scores, source: :user

  validates :kind, presence: true
  validates :title, presence: true
  validates :content, presence: true

  mount_uploader :resource_file, ResourceFileUploader

  def authorize
    unless can? :manage, @course_resource
      redirect_to root_path, alert: "Access denied buddy!"
    end
  end


end

app/models/course_unit.rb
class CourseUnit < ActiveRecord::Base

   has_many :course_resources, dependent: :nullify
   belongs_to :course

   has_many :syllabuses
   has_many :syllabulized_courses, through: :syllabuses, source: :course

   def authorize
     unless can? :manage, @course_unit
       redirect_to root_path, alert: "Access denied buddy!"
     end
   end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitee, class_name: "User"
  belongs_to :inviter, class_name: "User"
  
  validates :inviter_id, presence: true
  belongs_to :course
  has_secure_token

  after_save :unique_token

  private

  def unique_token
    invitations = Invitation.where("token = ?", token)
    regenerate_token unless invitations.length == 1
    unique_token unless invitations.length == 1
  end

  def self.email_absent? email
    !Invitation.where(email: email).present?
  end
end

app/models/kind.rb
class Kind < ActiveRecord::Base

  has_many :course_resources, dependent: :destroy
end

app/models/password_request.rb
class PasswordRequest < ActiveRecord::Base

  has_secure_token
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  validates :user_id, uniqueness: {scope: :course_resource_id}
end

app/models/studying.rb
class Studying < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  mount_uploader :file, ResourceFileUploader

end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  belongs_to :course
  belongs_to :course_unit

  validates :course_unit_id, uniqueness: {scope: :course_id}
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: :true, uniqueness: true,
            format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_secure_password

  mount_uploader :avatar, ImageUploader

  has_many :password_requests, dependent: :destroy

  has_many :invitees, through: :sent_invites, source: :invitee
  has_many :sent_invites, class_name: "Invitation", foreign_key: :inviter_id,
                  dependent: :destroy
  has_many :inviters, through: :received_invites, source: :inviter
  has_many :received_invites, class_name: "Invitation", foreign_key: :invitee_id,
                  dependent: :destroy

  has_many :submissions, dependent: :destroy

  has_many :studyings, dependent: :destroy
  has_many :studied_courses, through: :studyings, source: :course

  has_many :teachings, dependent: :destroy
  has_many :taught_courses, through: :teachings, source: :course

  has_many :scores, dependent: :destroy
  has_many :scored_courses, through: :scores, source: :course_resource

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(" ")
  end

  def self.email_absent? email
    !User.where(email: email).present?
  end

  def admin?
    admin == true
  end

end

app/controllers/course_units_controller.rb
class CourseUnitsController < ApplicationController

  before_action :find_course_unit, only: [:edit, :update, :destroy, :show]

  def index
    @course_units = CourseUnit.all
  end

  def new
    @course_unit = CourseUnit.new
  end

  def create
    @course_unit = CourseUnit.new(course_unit_params)
    if @course_unit.save
      redirect_to course_unit_path(@course_unit), notice: "Course Unit Created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course_unit.update(course_unit_params)
      redirect_to course_unit_path(@course_unit), notice: "Course Unit Updated"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    # CURRENTLY JUST NULLIFIES CHILDREN COURSE RESOURCES
    @course_unit.destroy
    redirect_to course_units_path, notice: "Course Unit Destroyed"
  end

  private

  def find_course_unit
    @course_unit ||= CourseUnit.find params[:id]
  end

  def course
    @course ||= Course.find_by_id(params[:course_id])
  end

  def course_unit_params
    params.require(:course_unit).permit([:title, :body])
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/course_units_helper.rb
module CourseUnitsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studyings_helper.rb
module StudyingsHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/course_units/_course_unit.html.erb
<% @course.course_units.each do |course_unit| %>
<div id="individual-course-unit">
		<ul>
		<li><h2><%= link_to course_unit.title, course_unit_path(course_unit) %></h2></li>
		<%= render "course_resources/resource", course_unit: course_unit %>
</div>
<% end %>

app/views/course_units/_form.html.erb
<% if @course_unit.errors.any? %>
  <ul>
    <% @course_unit.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="jumbotron-white">
  <div class="sign-up-form col-md-4">
  <table>
    <tr>
    <%= simple_form_for [@course, @course_unit] do |f| %>
      <th class="sign-up-form-field">
        <%= f.input :title %>
      </th>
    </tr>
    <tr>
      <th class="sign-up-form-field">
        <%= f.input :body %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.submit "Create Unit", class: "btn btn-success" %>
      </th>
    </tr>

    <% end %>
  </table>
  </div>
</div>

app/views/course_units/edit.html.erb
<H1> Edit The Course Unit</h1>

  <%= render "form"  %>

app/views/course_units/index.html.erb
<h1>Course Units</h1>
<li role="presentation" class="label-warning"><%= link_to "Create a new Course Unit", new_course_unit_path%></li>
  <!--There is an id number in the path for testing purposes only! This is temporary.-->
<li role="presentation" class="label-warning"><%= link_to "Edit a Course Unit", edit_course_unit_path(1) %></li>
<hr>

<div class="container container-welcome">
  <% @course_units.each do |course_unit| %>
  <table>
    <tr>
    <th><h2><%= link_to course_unit.title, course_unit_path(course_unit) %><h2></th>
    </tr>
    <div class="container">
      <% course_unit.course_resources.each do |resource| %>
      <tr>
        <td><%= link_to resource.title, course_unit_course_resource_path(course_unit, resource) %></td>
      </tr>
      <% end %>
    </div>
    <hr>
  </table>
  <% end %>
  </div>

app/views/course_units/new.html.erb
<H1> Create New Course Unit</h1>

  <%= render "form"  %>

app/views/course_units/show.html.erb
<%#= render "courses/nav" %>

<h1>Course Unit: <%= @course_unit.title %></h1>
<p>Description:<%= @course_unit.body %></p>
<% if can?(:manage, @course_unit) %>
<%= link_to "Edit", edit_course_unit_path(@course_unit) %>
<%= link_to "Delete", course_unit_path(@course_unit), method: :delete, data: {confirm: "Are you sure"} %>
<% end %>
<%= link_to "Add This Unit to a Course", courses_path %>,
<%= link_to "Add Course Resource", new_course_unit_course_resource_path(@course_unit) %>

<%# render "/course_resources/resource" %>
<!-- <ul class="sortable">
  <% @course_unit.course_resources.each do |course| %>
    <li><%= course.title %></li>
    <li><%= course.content %></li>
    <%= link_to "enter", course_resource_path(course) %>
  <% end %>
</ul> -->