config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  resources :courses do
    resources :course_units
    resources :teachings, only: [:create, :destroy]
    resources :studyings, only: [:create, :destroy]
    resources :invitations, only: [:create, :destroy]
  end

  resources :users, except: [:edit, :update] do
    get :edit, on: :collection
    patch :update, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :course_resources do
    resources :submissions
  end

 resources :contact

 resources :kinds

 resources :course_units do
   resources :course_resources
 end

 resources :password_requests, only: [:new, :create]

 get "password/reset" => "password_requests#reset"

 resources :scores, only: [:create, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    # When admin will be defined, un-comment it
    # if user.admin?
    #   can :manage, :all
    can :manage, CourseUnit do |course_unit|
      user.admin?
    end

    can :manage, CourseResource do |course_resouce|
      user.admin?
    end
    can :manage, Course do |course|
      user.admin?
    end
    can :manage, Kind do |kind|
      user.admin?
    end
    # else

    #  can :manage, CourseUnit do |unit|
    #    unit.user == user
    #  end

    #  can :manage, CourseResource do |resource|
    #    resource.unit.user == user || resource.user == user
    #  end

    # end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/course.rb
class Course < ActiveRecord::Base

	mount_uploader :course_logo, ImageUploader

  belongs_to :user

	has_many :invitations, dependent: :destroy
	has_many :invitees, through: :invitations, source: :invitee
	has_many :teachings, dependent: :destroy
	has_many :teachers, through: :teachings, source: :user

	has_many :studyings, dependent: :destroy
	has_many :students, through: :studyings, source: :user

	has_many :course_units, dependent: :destroy
	has_many :course_resources, through: :course_units

	has_many :invitations, dependent: :destroy

	has_many :syllabuses, dependent: :destroy
	has_many :course_unit_syllabulized, through: :syllabuses, source: :course_unit

  def study_for(user)
    studyings.find_by_user_id(user)
  end

  def teach_for(user)
    teachings.find_by_user_id(user)
  end

end

app/models/course_resource.rb
class CourseResource < ActiveRecord::Base

  belongs_to :kind
  belongs_to :course_unit

  has_many :submissions

  has_many :scores, dependent: :destroy
  has_many :scored_users, through: :scores, source: :user

  validates :kind, presence: true
  validates :title, presence: true
  validates :content, presence: true

  mount_uploader :resource_file, ResourceFileUploader

  def authorize
    unless can? :manage, @course_resource
      redirect_to root_path, alert: "Access denied buddy!"
    end
  end


end

app/models/course_unit.rb
class CourseUnit < ActiveRecord::Base

   has_many :course_resources, dependent: :nullify
   belongs_to :course

   has_many :syllabuses
   has_many :syllabulized_courses, through: :syllabuses, source: :course

   def authorize
     unless can? :manage, @course_unit
       redirect_to root_path, alert: "Access denied buddy!"
     end
   end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitee, class_name: "User"
  belongs_to :inviter, class_name: "User"
  
  validates :inviter_id, presence: true
  belongs_to :course
  has_secure_token

  after_save :unique_token

  private

  def unique_token
    invitations = Invitation.where("token = ?", token)
    regenerate_token unless invitations.length == 1
    unique_token unless invitations.length == 1
  end

  def self.email_absent? email
    !Invitation.where(email: email).present?
  end
end

app/models/kind.rb
class Kind < ActiveRecord::Base

  has_many :course_resources, dependent: :destroy
end

app/models/password_request.rb
class PasswordRequest < ActiveRecord::Base

  has_secure_token
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  validates :user_id, uniqueness: {scope: :course_resource_id}
end

app/models/studying.rb
class Studying < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  mount_uploader :file, ResourceFileUploader

end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  belongs_to :course
  belongs_to :course_unit

  validates :course_unit_id, uniqueness: {scope: :course_id}
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: :true, uniqueness: true,
            format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_secure_password

  mount_uploader :avatar, ImageUploader

  has_many :password_requests, dependent: :destroy

  has_many :invitees, through: :sent_invites, source: :invitee
  has_many :sent_invites, class_name: "Invitation", foreign_key: :inviter_id,
                  dependent: :destroy
  has_many :inviters, through: :received_invites, source: :inviter
  has_many :received_invites, class_name: "Invitation", foreign_key: :invitee_id,
                  dependent: :destroy

  has_many :submissions, dependent: :destroy

  has_many :studyings, dependent: :destroy
  has_many :studied_courses, through: :studyings, source: :course

  has_many :teachings, dependent: :destroy
  has_many :taught_courses, through: :teachings, source: :course

  has_many :scores, dependent: :destroy
  has_many :scored_courses, through: :scores, source: :course_resource

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(" ")
  end

  def self.email_absent? email
    !User.where(email: email).present?
  end

  def admin?
    admin == true
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_action :find_course, only: [:edit, :update, :destroy, :show]

	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new course_params
		if @course.save
			redirect_to course_path(@course)
		else
			render :new
		end
	end

	def show
		@course = Course.find params[:id]
		@course_units = @course.course_unit_syllabulized
		@students = @course.students
		@course_resources = @course.course_resources
	end

	def edit
	end

	def update
		if @course.update(course_params)
			redirect_to course_path(@course)
		else
			render :edit
		end
	end

	def destroy
		@course.destroy
		redirect_to courses_path(@course), notice: "Course Deleted"
	end

	private

	def find_course
		@course = Course.find params[:id]
	end

	def course_params
		params.require(:course).permit([:name, :description, :course_logo, {course_unit_ids: []}, {course_unit_syllabulized_ids: []}])
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studyings_helper.rb
module StudyingsHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>


<div class="sign-up-form col-md-4">
  <table>
    <tr>
      <th>
        <%= f.input :name, label_html: { class: 'sign-up-form-field' } %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.input :description, label_html: { class: 'sign-up-form-field' }%>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.collection_check_boxes :course_unit_ids, CourseUnit.all, :id, :title, label_html: { class: 'sign-up-form-field' }%>
      </th>
    </tr>
    <tr>
      <th>
        <br>
        <%= f.input :course_logo, label_html: { class: 'sign-up-form-field' }%>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.submit class: "btn btn-success" %>
      </th>
    </tr>
  </table>


</div>

<% end %>

app/views/courses/_nav.html.erb
<div class="course-nav" style= "margin-top: 20px;">
	<% if @course.present? && @course_unit.present? %>
	<%= link_to "Course", course_path(@course) %> //
		<%= link_to "Course Unit", course_unit_path(@course_unit) %>
	<% else %>
		Course: <%= link_to @course.name, course_path(@course) %> //
	<% end %>
</div>

app/views/courses/edit.html.erb
<h1> Modify a Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1>Courses</h1>
<li role="presentation" class="label-warning"><%= link_to "Create a Course", new_course_path %></li>
<li role="presentation" class="label-warning"><%= link_to "Edit a Course", edit_course_path(1) %></li>
<li role="presentation" class="label-warning"><%= link_to "Show Course", course_path(1) %></li>
<hr>
<ul>
  <% @courses.each do |course| %>
    <li><%= link_to course.name, course_path(course) %></li>
  <% end %>
</ul>

app/views/courses/new.html.erb
<div class="container">
    <div class="jumbotron-white">
    
    <h1> Create a New Course</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/courses/show.html.erb
<%= render "courses/nav", course: @course %>

<h2><%= @course.name %></h2>
<p>
  <%= @course.description %>
</p>

<!-- Assignment Progress -->
<!-- Why is this here? -->
<% if @course.students.include? current_user %>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: user_percentage%;">
      <span class="sr-only">60% Complete</span>
    </div>
  </div>
  <% if @course.course_resources.count > 0 %>
    <!-- progress bar result ** TO DO, qualify progress per specific course and divide in method -->
    <%= user_percentage = (Score.where(complete: true, user_id: current_user).count / @course.course_resources.count)*100 %> %
  <% end %>
<% end %>
 <%# if @user.admin == true %>
 <%# end %>

<% if current_user && current_user.admin? %>
  <%= render "/invitations/form" %>
<% end %>
<div class="container">
    <h1>Units</h1>
    <%= render "/course_units/course_unit" %>
</div>
<% if current_user && current_user.admin? %>
  <div class="courses-crud">
    <ul class="nav nav-tabs">
      <li><%= button_to "Edit Course", edit_course_path, class: "btn btn-success", method: :get %></li>
      <li>  <%= button_to "Delete Course", course_path(@course), class: "btn btn-success", method: :delete,
                data: {confirm: "Do you really want to delete this course?"} %></li>
      <li><%= button_to "Add New Course Unit", new_course_course_unit_path(:course_id), class: "btn btn-success", method: :get %></li>
    </ul>
  </div>
<% end %>
<br>