config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  resources :courses do
    resources :course_units
    resources :teachings, only: [:create, :destroy]
    resources :studyings, only: [:create, :destroy]
    resources :invitations, only: [:create, :destroy]
  end

  resources :users, except: [:edit, :update] do
    get :edit, on: :collection
    patch :update, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :course_resources do
    resources :submissions
  end

 resources :contact

 resources :kinds

 resources :course_units do
   resources :course_resources
 end

 resources :password_requests, only: [:new, :create]

 get "password/reset" => "password_requests#reset"

 resources :scores, only: [:create, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    # When admin will be defined, un-comment it
    # if user.admin?
    #   can :manage, :all
    can :manage, CourseUnit do |course_unit|
      user.admin?
    end

    can :manage, CourseResource do |course_resouce|
      user.admin?
    end
    can :manage, Course do |course|
      user.admin?
    end
    can :manage, Kind do |kind|
      user.admin?
    end
    # else

    #  can :manage, CourseUnit do |unit|
    #    unit.user == user
    #  end

    #  can :manage, CourseResource do |resource|
    #    resource.unit.user == user || resource.user == user
    #  end

    # end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/course.rb
class Course < ActiveRecord::Base

	mount_uploader :course_logo, ImageUploader

  belongs_to :user

	has_many :invitations, dependent: :destroy
	has_many :invitees, through: :invitations, source: :invitee
	has_many :teachings, dependent: :destroy
	has_many :teachers, through: :teachings, source: :user

	has_many :studyings, dependent: :destroy
	has_many :students, through: :studyings, source: :user

	has_many :course_units, dependent: :destroy
	has_many :course_resources, through: :course_units

	has_many :invitations, dependent: :destroy

	has_many :syllabuses, dependent: :destroy
	has_many :course_unit_syllabulized, through: :syllabuses, source: :course_unit

  def study_for(user)
    studyings.find_by_user_id(user)
  end

  def teach_for(user)
    teachings.find_by_user_id(user)
  end

end

app/models/course_resource.rb
class CourseResource < ActiveRecord::Base

  belongs_to :kind
  belongs_to :course_unit

  has_many :submissions

  has_many :scores, dependent: :destroy
  has_many :scored_users, through: :scores, source: :user

  validates :kind, presence: true
  validates :title, presence: true
  validates :content, presence: true

  mount_uploader :resource_file, ResourceFileUploader

  def authorize
    unless can? :manage, @course_resource
      redirect_to root_path, alert: "Access denied buddy!"
    end
  end


end

app/models/course_unit.rb
class CourseUnit < ActiveRecord::Base

   has_many :course_resources, dependent: :nullify
   belongs_to :course

   has_many :syllabuses
   has_many :syllabulized_courses, through: :syllabuses, source: :course

   def authorize
     unless can? :manage, @course_unit
       redirect_to root_path, alert: "Access denied buddy!"
     end
   end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitee, class_name: "User"
  belongs_to :inviter, class_name: "User"
  
  validates :inviter_id, presence: true
  belongs_to :course
  has_secure_token

  after_save :unique_token

  private

  def unique_token
    invitations = Invitation.where("token = ?", token)
    regenerate_token unless invitations.length == 1
    unique_token unless invitations.length == 1
  end

  def self.email_absent? email
    !Invitation.where(email: email).present?
  end
end

app/models/kind.rb
class Kind < ActiveRecord::Base

  has_many :course_resources, dependent: :destroy
end

app/models/password_request.rb
class PasswordRequest < ActiveRecord::Base

  has_secure_token
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  validates :user_id, uniqueness: {scope: :course_resource_id}
end

app/models/studying.rb
class Studying < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_resource

  mount_uploader :file, ResourceFileUploader

end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  belongs_to :course
  belongs_to :course_unit

  validates :course_unit_id, uniqueness: {scope: :course_id}
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  validates :user_id, uniqueness: {scope: :course_id}
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: :true, uniqueness: true,
            format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_secure_password

  mount_uploader :avatar, ImageUploader

  has_many :password_requests, dependent: :destroy

  has_many :invitees, through: :sent_invites, source: :invitee
  has_many :sent_invites, class_name: "Invitation", foreign_key: :inviter_id,
                  dependent: :destroy
  has_many :inviters, through: :received_invites, source: :inviter
  has_many :received_invites, class_name: "Invitation", foreign_key: :invitee_id,
                  dependent: :destroy

  has_many :submissions, dependent: :destroy

  has_many :studyings, dependent: :destroy
  has_many :studied_courses, through: :studyings, source: :course

  has_many :teachings, dependent: :destroy
  has_many :taught_courses, through: :teachings, source: :course

  has_many :scores, dependent: :destroy
  has_many :scored_courses, through: :scores, source: :course_resource

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(" ")
  end

  def self.email_absent? email
    !User.where(email: email).present?
  end

  def admin?
    admin == true
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studyings_helper.rb
module StudyingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>
<nav>
  <div class="logo"><%= link_to image_tag("logo.png"), root_path %></div>
  <ul class="nav nav-tabs">

    <li><span class="user-greeting">

  <% if current_user %>
      Hello <%= current_user.first_name %>,
       <% if current_user.avatar.present? %>
        <div>
           <%= image_tag(current_user.avatar.square_thumb.url, class: "img-circle animated bounce") %>
        </div>
       <% end %>
       <%= link_to 'Log Out', sessions_path, method: :delete,
            data: { confirm: 'Are you sure you want to log out?' }%></span></li>

          <li role="presentation" class="label-warning"><%= link_to 'Contact Us', contact_index_path %></li>

          <li role="presentation" class="label-warning"><%= link_to "Courses", courses_path %></li>

          <li role="presentation" class="label-warning"><%= link_to "Show Profile", current_user %></li>

          <li role="presentation" class="label-warning"><%= link_to "Course Units", course_units_path %></li>

   <% else %>
                <!-- Links if not signed in -->
          <li role="presentation" class="label-warning"><%= link_to 'Contact Us', contact_index_path %></li>
          <li role="presentation" class="label-warning"><%= link_to "Log in", new_session_path %></li>


   <% end %>
    </ul>
  </nav>
  <div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>

  </div>

  <!-- Begin footer jumbotron-green -->
<footer>
  <div class="jumbotron-green">
    <div class="col-md-4">
      <h3>CodeCore Bootcamp</h3> <p>
        142 W Hastings St<br>
        Vancouver, BC<br>
        V6B 1G8
      </p>
      <p>
        Phone: (604) 559-2633
      </p>
    </div>
  <div class="col-md-4">
    <h3>Hours</h3>
    <p>
    <table>
        <tr>
          <th>Monday&nbsp;&nbsp;</th>
          <th>8:00 am – 8:00 pm</th>
        </tr>
        <tr>
          <td>Tuesday&nbsp;&nbsp;</td>
          <td>8:00 am – 8:00 pm</td>
        </tr>
        <tr>
          <td>Wednesday&nbsp;&nbsp;</td>
          <td>8:00 am – 8:00 pm</td>
        </tr>
        <tr>
          <td>Thursday&nbsp;&nbsp;</td>
          <td>8:00 am – 8:00 pm</td>
        </tr>
        <tr>
          <td>Friday&nbsp;&nbsp;</td>
          <td>8:00 am – 8:00 pm</td>
        </tr>
        <tr>
          <td>Saturday&nbsp;&nbsp;</td>
          <td>11:00 am – 4:00 pm</td>
        </tr>
        <tr>
          <td>Sunday&nbsp;&nbsp;</td>
          <td>Closed</td>
        </tr>
    </table>
    </p>
  </div>


  <div class="col-md-4">
    <h3>Follow us</h3>
    <span>
      <%= link_to image_tag("social/facebook.png"), "https://www.facebook.com/CodeCoreBootcamp" %>
      <%= link_to image_tag("social/twitter.png"), "https://twitter.com/codecoreyvr" %>
    </span>
  </div>
</div>
</div>

  <!-- Begin copyright bar -->
  <div class="copyright">
    <div class="col-lg-12">
      <span>Copyright © 2015 CodeCore Bootcamp</span>
    </div>
  </div>

</footer>
</body>
</html>